# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventStatusSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_status', models.CharField(choices=[('NE', 'no event'), ('TD', 'to diler'), ('TS', 'to storage'), ('TP', 'to person'), ('TM', 'to_market'), ('FD', 'return from diler'), ('FP', 'return from person'), ('FM', 'return from market')], default='NE', max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerStatusSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.IntegerField(default=0)),
                ('m2', models.IntegerField(default=0)),
                ('m3', models.IntegerField(default=0)),
                ('m4', models.IntegerField(default=0)),
                ('m5', models.IntegerField(default=0)),
                ('m6', models.IntegerField(default=0)),
                ('m7', models.IntegerField(default=0)),
                ('m8', models.IntegerField(default=0)),
                ('m9', models.IntegerField(default=0)),
                ('m10', models.IntegerField(default=0)),
                ('w1', models.IntegerField(default=0)),
                ('w2', models.IntegerField(default=0)),
                ('w3', models.IntegerField(default=0)),
                ('w4', models.IntegerField(default=0)),
                ('w5', models.IntegerField(default=0)),
                ('w6', models.IntegerField(default=0)),
                ('w7', models.IntegerField(default=0)),
                ('w8', models.IntegerField(default=0)),
                ('w9', models.IntegerField(default=0)),
                ('w10', models.IntegerField(default=0)),
                ('ms', models.IntegerField(default=0)),
                ('ws', models.IntegerField(default=0)),
                ('ds', models.IntegerField(default=0)),
                ('mt', models.IntegerField(default=0)),
                ('wt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Partner')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProductSet')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EventStatusSet')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProductSet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Request')),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Transaction'),
        ),
        migrations.AddField(
            model_name='partner',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PartnerStatusSet'),
        ),
    ]
